import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.text.NumberFormat;
import java.util.Locale;

public class PagarDeudaDialog extends java.awt.Frame {
    
    
    private int rutDeudor;
    private String nombreDeudor;
    private int deudaTotal;
    private java.awt.Frame parentFrame;
    
    private String usuario;
    private boolean permisos;
    
    private int idBoletaEspecifica = -1; 
    
    private String URL = "jdbc:mysql://localhost:3306/vistaalmar";
    private String USUARIO = "root";
    private String PASSWORD = "";
    
    
    public PagarDeudaDialog(java.awt.Frame parent, int rutDeudor, String nombreDeudor, int deudaTotal, 
                            String usuario, boolean permisos, int idBoletaEspecifica) {
        this(parent, rutDeudor, nombreDeudor, deudaTotal, usuario, permisos);
        this.idBoletaEspecifica = idBoletaEspecifica; 
    }
    
    public PagarDeudaDialog(java.awt.Frame parent, int rutDeudor, String nombreDeudor, int deudaTotal) {
        this(parent, rutDeudor, nombreDeudor, deudaTotal, "usuario_desconocido", true);
    }
    
    public PagarDeudaDialog(java.awt.Frame parent, int rutDeudor, String nombreDeudor, int deudaTotal , String usuario , boolean permisos) {
        super();
        this.parentFrame = parent;
        this.rutDeudor = rutDeudor;
        this.nombreDeudor = nombreDeudor;
        this.deudaTotal = deudaTotal;
        this.usuario = usuario;
        this.permisos = permisos;
        initComponents();
        configurarComponentes();
        cargarUsuarios();
        agregarListeners();
        configurarSegunPermisos();
        setLocationRelativeTo(parent);
    }    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblRut = new javax.swing.JLabel();
        lblDeuda = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        lblCajero = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        lblNomCliente = new javax.swing.JLabel();
        lblMontoTotal = new javax.swing.JLabel();
        lblRutCliente = new javax.swing.JLabel();
        txtMontoAPagar = new javax.swing.JTextField();
        cmbRutCajero = new javax.swing.JComboBox<>();
        btnProcesar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("Pagar Deuda");

        lblCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCliente.setText("Cliente:");

        lblRut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRut.setText("RUT:");

        lblDeuda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDeuda.setText("Deuda Total:");

        lblMonto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMonto.setText("Monto a Pagar ($) :");

        lblCajero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCajero.setText("Cajero (Rut): ");

        lblTitulo2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo2.setText("Informacion del Pago");

        lblNomCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNomCliente.setForeground(new java.awt.Color(255, 0, 51));
        lblNomCliente.setText("NomExample");

        lblMontoTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMontoTotal.setForeground(new java.awt.Color(255, 0, 51));
        lblMontoTotal.setText("montoExample1000");

        lblRutCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRutCliente.setForeground(new java.awt.Color(255, 0, 51));
        lblRutCliente.setText("RutExample");

        cmbRutCajero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRutCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRutCajeroActionPerformed(evt);
            }
        });

        btnProcesar.setBackground(new java.awt.Color(0, 204, 51));
        btnProcesar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnProcesar.setForeground(new java.awt.Color(255, 255, 255));
        btnProcesar.setText("Procesar Pago");

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnProcesar)
                .addGap(56, 56, 56)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 87, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblRut, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblRutCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblMonto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbRutCajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMontoAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(lblTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(lblTitulo2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTitulo)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(lblNomCliente))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRut)
                    .addComponent(lblRutCliente))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeuda)
                    .addComponent(lblMontoTotal))
                .addGap(52, 52, 52)
                .addComponent(lblTitulo2)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMonto)
                    .addComponent(txtMontoAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCajero)
                    .addComponent(cmbRutCajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void configurarSegunPermisos() {
        setTitle("Pagar Deuda - Usuario: " + usuario);
        
        if (!permisos) {
            btnProcesar.setEnabled(true);
            btnProcesar.setToolTipText("");
        }
    }
    private void configurarComponentes() {
        lblNomCliente.setText(nombreDeudor);
        lblRutCliente.setText(String.valueOf(rutDeudor));
        
        NumberFormat nf = NumberFormat.getInstance(new Locale("es", "CL"));
        lblMontoTotal.setText("$" + nf.format(deudaTotal));
        
        btnProcesar.setBackground(new Color(34, 139, 34)); // Verde
        btnProcesar.setForeground(Color.WHITE);
        
        btnCancelar.setBackground(new Color(220, 20, 60)); // Rojo
        btnCancelar.setForeground(Color.WHITE);
        
        btnProcesar.setFocusPainted(false);
        btnCancelar.setFocusPainted(false);
        
        btnProcesar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnCancelar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }   
    
    
    private void cargarUsuarios() {
        cmbRutCajero.removeAllItems();
        cmbRutCajero.addItem("Seleccione...");

        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            System.out.println("DEBUG: Driver cargado");

            conn = DriverManager.getConnection(URL, USUARIO, PASSWORD);
            System.out.println("DEBUG: Conexión establecida");

            String checkTableQuery = "SHOW TABLES LIKE 'usuarios'";
            stmt = conn.createStatement();
            rs = stmt.executeQuery(checkTableQuery);

            if (!rs.next()) {
                System.out.println("DEBUG: La tabla 'usuarios' NO existe");
                JOptionPane.showMessageDialog(this,
                    "La tabla 'usuarios' no existe en la base de datos.\n" +
                    "Contacte al administrador del sistema.",
                    "Error de Configuración",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            System.out.println("DEBUG: La tabla 'usuarios' existe");

            String checkColumnsQuery = "DESCRIBE usuarios";
            rs = stmt.executeQuery(checkColumnsQuery);
            System.out.println("DEBUG: Estructura de la tabla usuarios:");
            while (rs.next()) {
                String columna = rs.getString("Field");
                String tipo = rs.getString("Type");
                System.out.println("  - " + columna + ": " + tipo);
            }
            rs.close();

            String sql = "SELECT rutUsuario, nomUsuario FROM usuarios ORDER BY nomUsuario";
            System.out.println("DEBUG: Ejecutando consulta: " + sql);

            rs = stmt.executeQuery(sql);
            int contadorUsuarios = 0;

            while (rs.next()) {
                int rutUsuario = rs.getInt("rutUsuario");
                String nombreUsuario = rs.getString("nomUsuario");
                cmbRutCajero.addItem(rutUsuario + " - " + nombreUsuario);
                contadorUsuarios++;
                System.out.println("DEBUG: Usuario cargado - RUT: " + rutUsuario + ", Nombre: " + nombreUsuario);
            }

            if (contadorUsuarios == 0) {
                System.out.println("DEBUG: No se encontraron usuarios");

                int respuesta = JOptionPane.showConfirmDialog(this,
                    "No hay usuarios registrados en el sistema.\n" +
                    "¿Desea crear un usuario de prueba automáticamente?",
                    "Sin Usuarios",
                    JOptionPane.YES_NO_OPTION);

                if (respuesta == JOptionPane.YES_OPTION) {
                    crearUsuarioDePrueba(conn);
                    cargarUsuarios();
                    return;
                } else {
                    cmbRutCajero.addItem("NO_HAY_USUARIOS - Contacte al administrador");
                }
            } else {
                System.out.println("DEBUG: Total usuarios cargados: " + contadorUsuarios);
            }

        } catch (ClassNotFoundException e) {
            System.err.println("ERROR: Driver MySQL no encontrado");
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Error: Driver MySQL no encontrado.\n" +
                "Asegúrese de tener el conector MySQL agregado al proyecto.",
                "Error de Driver",
                JOptionPane.ERROR_MESSAGE);

            cmbRutCajero.addItem("12345678 - Error de conexión");

        } catch (SQLException e) {
            System.err.println("ERROR SQL al cargar usuarios: " + e.getMessage());
            e.printStackTrace();

            String mensajeError;
            if (e.getMessage().contains("Unknown column")) {
                mensajeError = "Error en nombres de columnas: " + e.getMessage() + 
                              "\n\nColumnas esperadas: rutUsuario, nomUsuario";
            } else if (e.getMessage().contains("Unknown database")) {
                mensajeError = "La base de datos no existe";
            } else if (e.getMessage().contains("Access denied")) {
                mensajeError = "Acceso denegado a la base de datos";
            } else if (e.getMessage().contains("Communications link failure")) {
                mensajeError = "No se puede conectar al servidor MySQL";
            } else {
                mensajeError = e.getMessage();
            }

            JOptionPane.showMessageDialog(this,
                "Error al cargar usuarios:\n" + mensajeError,
                "Error de Base de Datos",
                JOptionPane.ERROR_MESSAGE);

            cmbRutCajero.addItem("12345678 - Error de BD");

        } finally {
            try {
                if (rs != null) rs.close();
                if (stmt != null) stmt.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    

    private void crearUsuarioDePrueba(Connection conn) {
        try {
            String insertSQL = "INSERT INTO usuarios (rutUsuario, nomUsuario, password) VALUES (?, ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(insertSQL);

            pstmt.setInt(1, 12345678);
            pstmt.setString(2, "Administrador");
            pstmt.setString(3, "1234");
            pstmt.executeUpdate();

            pstmt.setInt(1, 87654321);
            pstmt.setString(2, "Cajero Principal");
            pstmt.setString(3, "1234");
            pstmt.executeUpdate();

            pstmt.close();

            System.out.println("DEBUG: Usuarios de prueba creados");
            JOptionPane.showMessageDialog(this,
                "Se han creado 2 usuarios de prueba:\n" +
                "• 12345678 - Administrador\n" +
                "• 87654321 - Cajero Principal\n\n" +
                "Contraseña: 1234",
                "Usuarios de Prueba Creados",
                JOptionPane.INFORMATION_MESSAGE);

        } catch (SQLException e) {
            System.err.println("Error al crear usuarios de prueba: " + e.getMessage());
            JOptionPane.showMessageDialog(this,
                "Error al crear usuarios de prueba: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void agregarListeners() {
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarPago();
            }
        });
        
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispose();
            }
        });
        
        txtMontoAPagar.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE && c != java.awt.event.KeyEvent.VK_DELETE) {
                    evt.consume();
                }
            }
        });
    }
    
    
    
    private void procesarPago() {
        if (txtMontoAPagar.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Por favor ingrese el monto a pagar",
                "Campo Requerido",
                JOptionPane.WARNING_MESSAGE);
            txtMontoAPagar.requestFocus();
            return;
        }

        int montoPagar;
        try {
            montoPagar = Integer.parseInt(txtMontoAPagar.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "El monto debe ser un número válido",
                "Error de Formato",
                JOptionPane.ERROR_MESSAGE);
            txtMontoAPagar.selectAll();
            txtMontoAPagar.requestFocus();
            return;
        }

        if (montoPagar <= 0) {
            JOptionPane.showMessageDialog(this,
                "El monto debe ser mayor a cero",
                "Monto Inválido",
                JOptionPane.WARNING_MESSAGE);
            txtMontoAPagar.selectAll();
            txtMontoAPagar.requestFocus();
            return;
        }

        if (cmbRutCajero.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this,
                "Por favor seleccione un cajero",
                "Campo Requerido",
                JOptionPane.WARNING_MESSAGE);
            cmbRutCajero.requestFocus();
            return;
        }

        String selectedItem = (String) cmbRutCajero.getSelectedItem();
        System.out.println("DEBUG: Item seleccionado: " + selectedItem);

        String rutUsuarioStr = selectedItem.split(" - ")[0];
        int rutUsuario = Integer.parseInt(rutUsuarioStr);

        System.out.println("DEBUG: RUT Usuario a procesar: " + rutUsuario);

        NumberFormat nf = NumberFormat.getInstance(new Locale("es", "CL"));
        if (montoPagar > deudaTotal) {
            int opcion = JOptionPane.showConfirmDialog(this,
                "El monto ingresado ($" + nf.format(montoPagar) + ") es mayor a la deuda total ($" + nf.format(deudaTotal) + ").\n" +
                "¿Desea continuar de todas formas?",
                "Confirmar Pago",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

            if (opcion != JOptionPane.YES_OPTION) {
                return;
            }
        }

        int confirmar = JOptionPane.showConfirmDialog(this,
            "¿Confirmar pago de $" + nf.format(montoPagar) + " para " + nombreDeudor + "?\n" +
            "Cajero: " + selectedItem,
            "Confirmar Pago",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

        if (confirmar == JOptionPane.YES_OPTION) {
            realizarPago(montoPagar, rutUsuario);
        }
    }
    

    private void realizarPago(int montoPagar, int rutUsuario) {
        Connection conn = null;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(URL, USUARIO, PASSWORD);
            conn.setAutoCommit(false);

            if (!existeUsuarioEnBD(conn, rutUsuario)) {
                JOptionPane.showMessageDialog(this,
                    "ERROR: El usuario con RUT " + rutUsuario + " no existe en la base de datos.\n" +
                    "Por favor seleccione un usuario válido de la lista.",
                    "Usuario No Encontrado",
                    JOptionPane.ERROR_MESSAGE);
                conn.rollback();
                return;
            }

            String sqlPago = "INSERT INTO pagoDeudas (rutDeudor, rutUsuario, fechaTramite, totalPagado) VALUES (?, ?, ?, ?)";

            try (PreparedStatement pstmt = conn.prepareStatement(sqlPago)) {
                pstmt.setInt(1, rutDeudor);
                pstmt.setInt(2, rutUsuario);
                pstmt.setTimestamp(3, Timestamp.valueOf(LocalDateTime.now()));
                pstmt.setInt(4, montoPagar);
                pstmt.executeUpdate();
                System.out.println("DEBUG: Pago registrado - rutUsuario: " + rutUsuario);
            }

            int boletaEspecificaId = obtenerBoletaEspecificaSiExiste();

            if (boletaEspecificaId > 0) {
                System.out.println("DEBUG: Pagando boleta específica ID: " + boletaEspecificaId);
                aplicarPagoABoletaEspecifica(conn, boletaEspecificaId, montoPagar);
            } else {
                System.out.println("DEBUG: Aplicando pago FIFO");
                aplicarPagoFIFO(conn, montoPagar);
            }

            conn.commit();

            NumberFormat nf = NumberFormat.getInstance(new Locale("es", "CL"));
            JOptionPane.showMessageDialog(this,
                "Pago de $" + nf.format(montoPagar) + " procesado exitosamente",
                "Pago Exitoso",
                JOptionPane.INFORMATION_MESSAGE);

            dispose();

        } catch (ClassNotFoundException | SQLException e) {
            if (conn != null) {
                try {
                    conn.rollback();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
            JOptionPane.showMessageDialog(this,
                "Error al procesar el pago: " + e.getMessage(),
                "Error de Base de Datos",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } finally {
            if (conn != null) {
                try {
                    conn.setAutoCommit(true);
                    conn.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }

    private void aplicarPagoABoletaEspecifica(Connection conn, int idBoleta, int montoPagar) throws SQLException {
        String sqlDeudaEspecifica = "SELECT d.deudaId, b.totalFiado, d.montoPagado " +
                                   "FROM deudas d " +
                                   "INNER JOIN boletas b ON d.idBoleta = b.idBoleta " +
                                   "WHERE d.rutDeudor = ? AND d.idBoleta = ? AND d.estaPagado = 0";

        PreparedStatement pstmt = conn.prepareStatement(sqlDeudaEspecifica);
        pstmt.setInt(1, rutDeudor);
        pstmt.setInt(2, idBoleta);
        ResultSet rs = pstmt.executeQuery();

        if (rs.next()) {
            int deudaId = rs.getInt("deudaId");
            int totalFiado = rs.getInt("totalFiado");
            int montoPagadoActual = rs.getInt("montoPagado");
            int saldoActual = totalFiado - montoPagadoActual;

            System.out.println("DEBUG: Boleta " + idBoleta + " - Saldo actual: $" + saldoActual);

            if (saldoActual <= 0) {
                System.out.println("DEBUG: Esta boleta ya está pagada completamente");
                return;
            }

            int pagoAplicado = Math.min(montoPagar, saldoActual);
            int nuevoMontoPagado = montoPagadoActual + pagoAplicado;
            boolean pagadoCompleto = (nuevoMontoPagado >= totalFiado);

            System.out.println("DEBUG: Aplicando $" + pagoAplicado + " a boleta " + idBoleta);

            String sqlUpdate = "UPDATE deudas SET montoPagado = ?, estaPagado = ? WHERE deudaId = ?";
            PreparedStatement pstmtUpdate = conn.prepareStatement(sqlUpdate);
            pstmtUpdate.setInt(1, nuevoMontoPagado);
            pstmtUpdate.setBoolean(2, pagadoCompleto);
            pstmtUpdate.setInt(3, deudaId);
            pstmtUpdate.executeUpdate();
            pstmtUpdate.close();

            int montoRestante = montoPagar - pagoAplicado;

            if (montoRestante > 0) {
                System.out.println("DEBUG: Sobra $" + montoRestante + ", aplicando a otras deudas");
                aplicarPagoFIFO(conn, montoRestante);
            }
        } else {
            System.out.println("DEBUG: Boleta específica no encontrada o ya pagada");
            aplicarPagoFIFO(conn, montoPagar);
        }

        rs.close();
        pstmt.close();
    }

    private void aplicarPagoFIFO(Connection conn, int montoPagar) throws SQLException {
        String sqlDeudas = "SELECT d.deudaId, b.totalFiado, d.montoPagado " +
                          "FROM deudas d " +
                          "INNER JOIN boletas b ON d.idBoleta = b.idBoleta " +
                          "WHERE d.rutDeudor = ? AND d.estaPagado = 0 " +
                          "ORDER BY d.fechaDeuda ASC";

        ArrayList<DeudaInfo> deudas = new ArrayList<>();

        try (PreparedStatement pstmt = conn.prepareStatement(sqlDeudas)) {
            pstmt.setInt(1, rutDeudor);
            ResultSet rs = pstmt.executeQuery();

            while (rs.next()) {
                DeudaInfo deuda = new DeudaInfo();
                deuda.deudaId = rs.getInt("deudaId");
                deuda.totalFiado = rs.getInt("totalFiado");
                deuda.montoPagado = rs.getInt("montoPagado");
                deuda.saldo = deuda.totalFiado - deuda.montoPagado;
                deudas.add(deuda);
            }
        }

        int montoRestante = montoPagar;
        String sqlUpdate = "UPDATE deudas SET montoPagado = ?, estaPagado = ? WHERE deudaId = ?";

        for (DeudaInfo deuda : deudas) {
            if (montoRestante <= 0) break;

            int pagoAplicado = Math.min(montoRestante, deuda.saldo);
            int nuevoMontoPagado = deuda.montoPagado + pagoAplicado;
            boolean pagadoCompleto = (nuevoMontoPagado >= deuda.totalFiado);

            try (PreparedStatement pstmt = conn.prepareStatement(sqlUpdate)) {
                pstmt.setInt(1, nuevoMontoPagado);
                pstmt.setBoolean(2, pagadoCompleto);
                pstmt.setInt(3, deuda.deudaId);
                pstmt.executeUpdate();
            }

            montoRestante -= pagoAplicado;
        }
    }

    private int obtenerBoletaEspecificaSiExiste() {
        return idBoletaEspecifica;
    }

    private boolean existeUsuarioEnBD(Connection conn, int rutUsuario) throws SQLException {
        try {
            String query = "SELECT COUNT(*) as count FROM usuarios WHERE rutUsuario = ?";
            PreparedStatement pstmt = conn.prepareStatement(query);
            pstmt.setInt(1, rutUsuario);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next() && rs.getInt("count") > 0) {
                rs.close();
                pstmt.close();
                System.out.println("DEBUG: Usuario encontrado: " + rutUsuario);
                return true;
            }
            rs.close();
            pstmt.close();

            System.out.println("DEBUG: Usuario NO encontrado - RUT: " + rutUsuario);
            return false;

        } catch (SQLException e) {
            System.err.println("Error en existeUsuarioEnBD: " + e.getMessage());
            throw e;
        }
    }  
    
    
    
    
    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        dispose();
    }//GEN-LAST:event_exitForm

    private void cmbRutCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRutCajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRutCajeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Para probar el diálogo
                PagarDeudaDialog dialog = new PagarDeudaDialog(null, 12345678, "Juan Pérez", 250000);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private static class DeudaInfo {
        int deudaId;
        int totalFiado;
        int montoPagado;
        int saldo;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JComboBox<String> cmbRutCajero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCajero;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDeuda;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblMontoTotal;
    private javax.swing.JLabel lblNomCliente;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblRutCliente;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JTextField txtMontoAPagar;
    // End of variables declaration//GEN-END:variables
}
